using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MailArchiver.Migrations
{
    /// <inheritdoc />
    public partial class MigrateV2509_7 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Check if AccessLogs table exists, create if it doesn't
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS mail_archiver.""AccessLogs"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Username"" text NOT NULL,
                    ""Type"" integer NOT NULL,
                    ""Timestamp"" timestamp without time zone NOT NULL,
                    ""EmailId"" integer,
                    ""EmailSubject"" text,
                    ""EmailFrom"" text,
                    ""SearchParameters"" text,
                    ""MailAccountId"" integer,
                    CONSTRAINT ""PK_AccessLogs"" PRIMARY KEY (""Id"")
                );
            ");
            
            // Add EmailFrom column if it doesn't exist
            migrationBuilder.Sql(@"
                DO $$ 
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 
                        FROM information_schema.columns 
                        WHERE table_schema = 'mail_archiver' 
                        AND table_name = 'AccessLogs' 
                        AND column_name = 'EmailFrom'
                    ) THEN
                        ALTER TABLE mail_archiver.""AccessLogs"" ADD COLUMN ""EmailFrom"" text;
                    END IF;
                END $$;
            ");
            
            // Create indexes for better performance (IF NOT EXISTS is supported in PostgreSQL 9.5+)
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_AccessLogs_Timestamp"" ON mail_archiver.""AccessLogs"" (""Timestamp"");
                CREATE INDEX IF NOT EXISTS ""IX_AccessLogs_Username"" ON mail_archiver.""AccessLogs"" (""Username"");
                CREATE INDEX IF NOT EXISTS ""IX_AccessLogs_Type"" ON mail_archiver.""AccessLogs"" (""Type"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Drop AccessLogs table
            migrationBuilder.Sql(@"
                DROP TABLE IF EXISTS mail_archiver.""AccessLogs"";
            ");
        }
    }
}
