using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MailArchiver.Migrations
{
    /// <inheritdoc />
    public partial class MigrateV2509_5 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Add ContentId column to EmailAttachments table if it doesn't exist
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_schema = 'mail_archiver' 
                                   AND table_name = 'EmailAttachments' 
                                   AND column_name = 'ContentId') THEN
                        ALTER TABLE mail_archiver.""EmailAttachments"" 
                        ADD COLUMN ""ContentId"" text;
                    END IF;
                END $$;
            ");

            // Remove legacy UserSessions table if it exists
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.tables 
                               WHERE table_schema = 'mail_archiver' 
                               AND table_name = 'UserSessions') THEN
                        DROP TABLE mail_archiver.""UserSessions"";
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Recreate UserSessions table (for rollback purposes)
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.tables 
                                   WHERE table_schema = 'mail_archiver' 
                                   AND table_name = 'UserSessions') THEN
                        CREATE TABLE mail_archiver.""UserSessions"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                            ""CreatedAt"" timestamp without time zone NOT NULL,
                            ""ExpiresAt"" timestamp without time zone,
                            ""Token"" character varying(255) NOT NULL,
                            ""Username"" character varying(50) NOT NULL,
                            CONSTRAINT ""PK_UserSessions"" PRIMARY KEY (""Id"")
                        );
                        
                        CREATE INDEX ""IX_UserSessions_ExpiresAt"" ON mail_archiver.""UserSessions"" (""ExpiresAt"");
                        CREATE UNIQUE INDEX ""IX_UserSessions_Token"" ON mail_archiver.""UserSessions"" (""Token"");
                        CREATE INDEX ""IX_UserSessions_Username"" ON mail_archiver.""UserSessions"" (""Username"");
                    END IF;
                END $$;
            ");

            // Remove ContentId column from EmailAttachments table if it exists
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.columns 
                               WHERE table_schema = 'mail_archiver' 
                               AND table_name = 'EmailAttachments' 
                               AND column_name = 'ContentId') THEN
                        ALTER TABLE mail_archiver.""EmailAttachments"" 
                        DROP COLUMN ""ContentId"";
                    END IF;
                END $$;
            ");
        }
    }
}
